import type { Config } from 'tailwindcss'

const config: Config = {
  content: [
    './pages/**/*.{js,ts,jsx,tsx,mdx}',
    './components/**/*.{js,ts,jsx,tsx,mdx}',
    './app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        // Existing CLAUDE.md colors
        bg: '#0a0805',
        surface: '#13100c',
        border: '#2a2218',
        gold: {
          DEFAULT: '#c9a84c',
          light: '#e8c97a',
        },
        text: '#f0ead8',
        muted: '#8a7d65',
        burgundy: '#6b1f2a',
        // Stitch Material Design 3 tokens
        background: '#16130f',
        'surface-container-lowest': '#100e0a',
        'surface-container-low': '#1e1b17',
        'surface-container': '#221f1b',
        'surface-container-high': '#2d2a25',
        'surface-container-highest': '#38342f',
        'surface-variant': '#38342f',
        'surface-bright': '#3c3934',
        'surface-dim': '#16130f',
        'surface-tint': '#e6c364',
        'on-surface': '#e8e1da',
        'on-surface-variant': '#d0c5b2',
        'on-background': '#e8e1da',
        primary: '#e6c364',
        'primary-container': '#c9a84c',
        'primary-fixed': '#ffe08f',
        'primary-fixed-dim': '#e6c364',
        'on-primary': '#3d2e00',
        'on-primary-container': '#503d00',
        'on-primary-fixed': '#241a00',
        'on-primary-fixed-variant': '#584400',
        secondary: '#ccc6b5',
        'secondary-container': '#4c493c',
        'secondary-fixed': '#e8e2d0',
        'secondary-fixed-dim': '#ccc6b5',
        'on-secondary': '#333125',
        'on-secondary-container': '#bdb8a8',
        'on-secondary-fixed': '#1e1c11',
        'on-secondary-fixed-variant': '#4a473a',
        tertiary: '#b9c4ff',
        'tertiary-container': '#9ba8eb',
        'tertiary-fixed': '#dde1ff',
        'tertiary-fixed-dim': '#b9c3ff',
        'on-tertiary': '#1e2b66',
        'on-tertiary-container': '#2e3b77',
        'on-tertiary-fixed': '#041451',
        'on-tertiary-fixed-variant': '#35437e',
        error: '#ffb4ab',
        'error-container': '#93000a',
        'on-error': '#690005',
        'on-error-container': '#ffdad6',
        outline: '#99907e',
        'outline-variant': '#4d4637',
        'inverse-surface': '#e8e1da',
        'inverse-on-surface': '#33302b',
        'inverse-primary': '#755b00',
      },
      fontFamily: {
        display: ['var(--font-cormorant)', 'serif'],
        body: ['var(--font-dm-sans)', 'sans-serif'],
        arabic: ['var(--font-noto-arabic)', 'serif'],
        'display-lg': ['EB Garamond', 'serif'],
        'headline-md': ['EB Garamond', 'serif'],
        'display-lg-mobile': ['EB Garamond', 'serif'],
        'body-md': ['DM Sans', 'sans-serif'],
        'body-lg': ['DM Sans', 'sans-serif'],
        'label-caps': ['DM Sans', 'sans-serif'],
        'arabic-headline': ['Noto Serif', 'serif'],
      },
      fontSize: {
        'display-lg': ['64px', { lineHeight: '1.1', letterSpacing: '-0.02em', fontWeight: '400' }],
        'headline-md': ['32px', { lineHeight: '1.3', fontWeight: '400' }],
        'display-lg-mobile': ['40px', { lineHeight: '1.2', fontWeight: '400' }],
        'body-md': ['16px', { lineHeight: '1.6', fontWeight: '400' }],
        'body-lg': ['18px', { lineHeight: '1.6', fontWeight: '400' }],
        'label-caps': ['12px', { lineHeight: '1', letterSpacing: '0.2em', fontWeight: '500' }],
        'arabic-headline': ['32px', { lineHeight: '1.5', fontWeight: '400' }],
      },
      spacing: {
        'container-max': '1440px',
        gutter: '1.5rem',
        'section-padding': '6rem',
        'stack-sm': '0.5rem',
        'stack-md': '1.5rem',
        'stack-lg': '3rem',
      },
      maxWidth: {
        'container-max': '1440px',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      keyframes: {
        shimmer: {
          '0%': { backgroundPosition: '-200% 0' },
          '100%': { backgroundPosition: '200% 0' },
        },
      },
      animation: {
        shimmer: 'shimmer 2s ease-in-out infinite',
      },
    },
  },
  plugins: [require('tailwindcss-animate')],
}

export default config
